version: '3.9'
services:
  db:
    image: postgres:16
    container_name: hr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: