spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrdb}?sslmode=${DB_SSLMODE:disable}
    username: ${DB_USER:hr}
    password: ${DB_PASSWORD:hr}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn